App\Entity\Location:
  properties:
    city:
      - NotBlank: { groups: [ 'create', 'edit' ] }
    country:
      - NotBlank: { groups: [ 'create', 'edit' ] }
    latitude:
      - NotBlank: { groups: [ 'create' ] }
      - Range:
          min: -90
          max: 90
          groups: [ 'create', 'edit' ]
    longitude:
      - NotBlank: { groups: [ 'create' ] }
      - Range:
          min: -180
          max: 180
          groups: [ 'create', 'edit' ]

App\Entity\Measurement:
  properties:
    celsius:
      - NotBlank: { groups: [ 'create', 'edit' ] }
      - Type: float
      - Range:
          min: -273.15
          groups: [ 'create', 'edit' ]
    location:
        - NotBlank: { groups: [ 'create', 'edit' ] }
    date:
        - NotBlank: { groups: [ 'create', 'edit' ] }
        - Type: datetime
        - GreaterThanOrEqual:
                  value: 'today'
                  groups: [ 'create', 'edit' ]
